### ISSUE TITLE
how to reduce latency on Mac OS ?

### ISSUE THREAD

**Issue by avilleret** [arturoc/ofxGstRTP#8]
I'm experiencing big latency on Mac OS X something like what I see with VLC 3 or 4 seconds.
The same code run fine with one image latency (16ms) on Linux.
Also I can open the stream on Mac OS with :

`gst-launch-1.0 udpsrc port=5000 ! application/x-rtp, payload=96r ! rtph264depay ! avdec_h264 ! fpsdisplaysink sync=false text-overlay=true``

And I can see any latency (so I guess this is the same as on Linux, 16ms or so).

How can I reach that very small latency with Gstreamer in OF ?
Changing the latency parameter doesn't do anything.
The stream comes from a Raspberry Pi with a `gst-launch` command line.
The code is here : https://github.com/avilleret/nebula-eye

Any hint is welcome :-)

**Comment by arturoc** [comment]
there is a setting that needs to be set before opening the stream, when calling setup on the client. that sets something like the maximum latency and then you can adjust the latency while the streaming is live.

take a look at the LAN example where it sets latency to 0 on setup: https://github.com/arturoc/ofxGstRTP/blob/master/example_video_audio_LAN/src/ofApp.cpp

**Comment by avilleret** [comment]
thanks @arturoc 
but the latency is already 0 in the setup call : https://github.com/avilleret/nebula-eye/blob/master/src/ofApp.cpp#L5
and this doesn't explain why the same code have different latency on different system.
maybe the Gstreamer version matter ? 
I'm using 1.0-1.2.1 (1.7.2 doesn't work but I don't know why yet) on Mac OS while on Linux it's 1.0-1.6.0

**Comment by arturoc** [comment]
i tried this with 1.2 originally but perhaps try something newer. not sure why the difference between osx and linux.

also i would try setting something other than 0 (perhaps 0 means auto latency or something like that) and then setting the latency through the latency ofParameter in ofxGstRTPClient, which by default is set to 200

**Comment by avilleret** [comment]
after some tests, it appears that GStreamer version matters 
using the latest one available today (1.7.1) on Mac OS 10.10 works fine.
I mean I get the same very low latency as with command line tool `gst-launch-1.0`
I guess version 1.6.x could work too (since my `gst-launch-1.0` tool is based on it)

maybe we should reflect this in the `README.md` ?

**Comment by arturoc** [comment]
yes, i haven't touched the readme in a while, if you want to update it to point to the latest version or even better to the root so people just install the last one whatever that is at any point? i used a specific one in case changes in the library broke compatibility but it's been 5 minor versions already and it keeps working without problem.

**Comment by avilleret** [comment]
done here : https://github.com/arturoc/ofxGStreamer/pull/11
